server:
  port: 8088
spring:
  application:
    name: eParking
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '@@nrot@@'
    url: jdbc:mysql://10.222.232.158:3306/parkinglot
    username: root
  jpa:
    database: MySQL
    generate-ddl: false
    show-sql: false
  profiles:
    active: local
